<a href="https://colab.research.google.com/github/dddevicom/i_hub_masai_moduel2/blob/main/Encode_Categorical_Columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [ ]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())

In [ ]:
mode_val = df['city'].mode()
df['city'] = df['city'].fillna(mode_val[0])

In [ ]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [ ]:
#df.drop_duplicates(subset=['customer_id'], keep='last')
df = df.drop_duplicates(keep='first')
df.reset_index(drop=True, inplace=True)

In [ ]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            5  40.0   Delhi    Male          95000

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# One-Hot Encoding on city
df = pd.get_dummies(df, columns=['city'], dtype=int)

# Label Encoding on gender
lable = LabelEncoder()
df['gender'] = lable.fit_transform(df['gender'])

print(df)

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000           0            1
1            2  35.0       0          80000           1            0
2            3  35.0       0          60000           1            0
3            4  35.0       1         120000           0            1
4            5  40.0       1          95000           1            0

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
cols_to_scale = ['age', 'annual_income']
# scaler = MinMaxScaler()
# df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])
# print("=== Min-Max Scaled ===")
# print(df)

minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[cols_to_scale] = minmax.fit_transform(df[cols_to_scale])
print("=== Min-Max Scaled ===")
print(df_minmax)

=== Min-Max Scaled ===
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000           0            1
1            2  0.666667       0         0.5000           1            0
2            3  0.666667       0         0.2500           1            0
3            4  0.666667       1         1.0000           0            1
4            5  1.000000       1         0.6875           1            0

In [ ]:
standard = StandardScaler()
df_standard = df.copy()
df_standard[cols_to_scale] = standard.fit_transform(df[cols_to_scale])
print("=== Standard Scaled ===")
print(df_standard)

=== Standard Scaled ===
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970           0            1
1            2  0.204124       0       0.036179           1            0
2            3  0.204124       0      -0.687396           1            0
3            4  0.204124       1       1.483328           0            1
4            5  1.224745       1       0.578860           1            0

**MinMaxScaler vs StandardScaler — When to Prefer Each**
Use MinMaxScaler when your algorithm strictly requires inputs in a bounded range — such as Neural Networks with sigmoid/tanh activations or image pixel normalization — and you are confident your data contains no significant outliers, because a single extreme value will compress every other value toward zero and distort the entire scale.
Use StandardScaler when your data may contain outliers, or when you are using algorithms rooted in statistical assumptions like Linear Regression, Logistic Regression, SVM, or PCA — these algorithms expect features centred around zero with consistent spread, which StandardScaler directly delivers without being sensitive to extreme values.
In practice, default to StandardScaler — real-world data almost always has outliers, and StandardScaler degrades gracefully whereas MinMaxScaler degrades catastrophically, so it is the safer and more robust choice unless you have a specific architectural reason to bound your inputs